Exception: element not in database works and gives element name. creating a function to only display 'add element' and adding more clarification for the user about which element is missing from database